package templates

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"
)

func TestPKGPath(t *testing.T) {
	tmp, err := Get("pkgpath")

	require.NoError(t, err)
	require.NotNil(t, tmp)

	p := &packages.Package{
		Name:    "abc123",
		PkgPath: "github.com/abc/a1/abc123",
		Module: &packages.Module{
			Path: "github.com/abc",
		},
	}

	s := strings.Builder{}
	err = tmp.Execute(&s, p)
	require.NoError(t, err)

	require.Equal(t, expectedPKGPath, s.String())
}

const expectedPKGPath = `// Code generated by pkgen; DO NOT EDIT.
package abc123

const PackagePath = "github.com/abc/a1/abc123"
const ModulePath = "github.com/abc"
`
